root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/main.go"
bin = "./tmp/main"
include_ext = ["go", "html"]
exclude_dir = ["assets", "tmp", "vendor", "tests"]

[cmd]
name = "./tmp/main"

[watch]
include = ["**/*.go"]
exclude = ["./tmp", "./vendor/**", "./tests/**"]
method = "poll"

[log]
# Show log time
time = true
# Only show main log (silences watcher, build, runner)
main_only = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
