# 使用更小的基础镜像
FROM golang:1.22-alpine as builder

# 设置工作目录
WORKDIR /app

# 设置Go Module代理
RUN go env -w GOPROXY=https://goproxy.cn,direct

# 复制go mod文件
COPY go.mod go.sum ./

# 下载依赖
RUN go mod download

# 复制所有文件到工作目录
COPY . .

# 构建应用
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/main.go

# 使用更小的运行时镜像
FROM alpine:latest as final
WORKDIR /root/

# 从构建阶段复制构建出的二进制文件
COPY --from=builder /app/main .

# 运行你的程序
CMD ["./main"]
